# Generated by Django 3.2.16 on 2023-04-09 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=50)),
                ('soil_pH', models.FloatField()),
                ('soil_texture', models.CharField(max_length=50)),
                ('avg_temp', models.FloatField()),
                ('sowing_month', models.CharField(max_length=20)),
                ('season', models.CharField(max_length=20)),
                ('crop_type', models.CharField(max_length=50)),
            ],
        ),
    ]
