# Generated by Django 3.2.16 on 2023-04-09 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crop_recommendation_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crop',
            old_name='soil_pH',
            new_name='soil_ph',
        ),
    ]
