# Generated by Django 3.2.16 on 2023-04-09 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crop_recommendation_app', '0002_rename_soil_ph_crop_soil_ph'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Crop',
        ),
    ]
